import os

class ReportGenerator:
    """
    Enhanced Reporting Layer: Generates deep-dive dashboard for the 7 quality dimensions.
    Compatible with both plain float scores and new Explainable Dimension Card dicts.
    """
    def __init__(self):
        self.base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    def _score(self, value):
        return value.get("score", 0.0) if isinstance(value, dict) else float(value)

    def _status(self, value):
        if isinstance(value, dict):
            return value.get("status", "N/A")
        s = float(value)
        return "PASS" if s >= 90 else "WARN" if s >= 70 else "FAIL"

    def _recommendation(self, value):
        if isinstance(value, dict):
            return value.get("recommendation", "")
        s = float(value)
        if s >= 90: return "High reliability; minimal to no data anomalies detected."
        if s >= 70: return "Acceptable but contains non-critical gaps or inconsistencies."
        return "Critical level of errors; data requires significant remediation."

    def _description(self, value):
        return value.get("description", "") if isinstance(value, dict) else ""

    def generate_summary(self, report):
        if not report:
            print("[!] Error: No report data to display.")
            return

        if report.get('status') == "No Data Found for this period":
            print("\n" + "!"*80)
            print("  [!] NO DATA FOUND FOR THIS DATE RANGE")
            print("  Please check your filter dates and try again.")
            print("!"*80 + "\n")
            return

        print("\n" + "╔" + "═"*78 + "╗")
        print("║" + " "*28 + "📍 MASTER QUALITY DASHBOARD" + " "*24 + "║")
        print("╠" + "═"*78 + "╣")
        print(f"║  OVERALL TRUSTABILITY SCORE: {report['overall_trustability']:>6}%" + " "*41 + "║")
        print("╠" + "─"*78 + "╢")

        for dim, value in report['dimensions'].items():
            score = self._score(value)
            bar = "█" * int(score / 10) + "░" * (10 - int(score / 10))
            print(f"║  {dim:<15} [{bar}] {score:>6}%" + " "*42 + "║")

        print("╚" + "═"*78 + "╝\n")

    def save_report(self, report, filename="final_quality_report.txt"):
        if not report:
            return None
        report_path = os.path.join(self.base_dir, "data", "processed", filename)

        explanation = (
            "This report provides a comprehensive analysis of the dataset using the "
            "7 Dimensions of Trustability. Our framework evaluates records for Completeness (missing data), "
            "Accuracy (statistical consistency), Validity (type compliance), Consistency (logical sequence), "
            "Uniqueness (duplicate reduction), Integrity (structural adherence), and Lineage (data origin). "
            "A high Trustability Score ensures that the data is reliable for downstream processing and AI-driven insights."
        )

        with open(report_path, "w", encoding="utf-8") as f:
            f.write("╔" + "═"*78 + "╗\n")
            f.write("║" + " "*28 + "DATA TRUSTABILITY REPORT" + " "*26 + "║\n")
            f.write("╚" + "═"*78 + "╝\n\n")

            f.write("--- EXECUTIVE SUMMARY ---\n")
            if report.get('status') == "No Data Found for this period":
                f.write("[!] NO DATA FOUND: No records were fetched or remained after remediation.\n")
                f.write("Please adjust the date filters in main.py.\n\n")
                return report_path

            f.write(explanation + "\n\n")
            f.write(f"Total Records Processed: {report['total_records']}\n")
            f.write(f"Overall Trustability:    {report['overall_trustability']}%\n\n")

            f.write("--- DIMENSION BREAKDOWN & REASONING ---\n")
            for dim, value in report['dimensions'].items():
                score = self._score(value)
                status = self._status(value)
                reason = self._recommendation(value)
                f.write(f"📍 {dim:<15}: {score:>6}% [{status}]\n")
                f.write(f"   Reasoning: {reason}\n\n")

            f.write("="*80 + "\n")
            f.write("Report generated by the Gesix Data Quality Framework.\n")

        print(f"[+] Detailed Technical Report saved: data/processed/{filename}")
        return report_path

    def save_html_report(self, report, filename="dashboard.html"):
        if not report:
            return None
        report_path = os.path.join(self.base_dir, "data", "processed", filename)

        STATUS_COLOR = {"PASS": "#27ae60", "WARN": "#f39c12", "FAIL": "#e74c3c"}

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gesix Data Trustability Dashboard</title>
    <style>
        body {{ font-family: sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
        header {{ border-bottom: 2px solid #2c3e50; padding-bottom: 10px; margin-bottom: 30px; }}
        .score-box {{ background: #f8f9fa; border-left: 5px solid #2c3e50; padding: 20px; margin-bottom: 20px; }}
        .dimensions-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; }}
        .dim-card {{ border: 1px solid #ddd; padding: 15px; border-radius: 8px; }}
        .badge {{ display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 0.8em; font-weight: bold; color: white; }}
        .desc {{ font-size: 0.85em; color: #555; margin: 6px 0; }}
        .impact {{ font-size: 0.82em; color: #777; border-left: 3px solid #ddd; padding-left: 8px; margin: 6px 0; }}
        .rec {{ font-size: 0.85em; font-style: italic; margin-top: 8px; }}
        .status-PASS {{ color: #27ae60; font-weight: bold; }}
        .status-WARN {{ color: #f39c12; font-weight: bold; }}
        .status-FAIL {{ color: #e74c3c; font-weight: bold; }}
    </style>
</head>
<body>
    <header>
        <h1>📊 Data Trustability Dashboard</h1>
        <p>Generated by Gesix Data Quality Framework</p>
    </header>

    <section class="control-panel" style="background: #eef2f3; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
        <h3>Run New Analysis</h3>
        <form action="/process" method="POST" style="display: flex; gap: 15px; align-items: flex-end; flex-wrap: wrap;">
            <div>
                <label for="start_date">Start Date:</label><br>
                <input type="date" id="start_date" name="start_date" required style="padding: 8px; border-radius: 4px; border: 1px solid #ccc;">
            </div>
            <div>
                <label for="end_date">End Date:</label><br>
                <input type="date" id="end_date" name="end_date" required style="padding: 8px; border-radius: 4px; border: 1px solid #ccc;">
            </div>
            <button type="submit" style="background: #2c3e50; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; font-weight: bold;">
                🚀 Process Data
            </button>
        </form>
    </section>

    <section class="score-box">
"""
        if report.get('status') == "No Data Found for this period":
            html_content += """
        <h2 style="color: #e74c3c;">[!] NO DATA FOUND</h2>
        <p>The pipeline successfully executed but found 0 records for the selected date range.</p>
        <p><strong>Action Required:</strong> Please check your start/end dates and run the pipeline again.</p>
    </section>
"""
        else:
            html_content += f"""
        <h2>Overall Trustability: <span id="overall-score">{report['overall_trustability']}%</span></h2>
        <p>Total Records Processed: <span id="total-count">{report['total_records']}</span></p>
    </section>

    <section class="dimensions-grid">
"""
            for dim, value in report['dimensions'].items():
                score     = self._score(value)
                status    = self._status(value)
                rec       = self._recommendation(value)
                desc      = self._description(value)
                color     = STATUS_COLOR.get(status, "#999")

                html_content += f"""
        <div class="dim-card" id="dim-{dim.lower()}">
            <h3>{dim} &nbsp;<span class="badge" style="background:{color};">{status}</span></h3>
            <p>Score: <strong>{score}%</strong></p>
            {"<p class='desc'>" + desc + "</p>" if desc else ""}
            {"<p class='rec'>💡 " + rec + "</p>" if rec else ""}
        </div>
"""

        html_content += """
    </section>

    <footer style="margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 0.8em; color: #777;">
        <p>End-to-End Backend Verification: COMPLETE</p>
    </footer>

    <script>
        document.querySelector('form').addEventListener('submit', function(e) {
            const btn = this.querySelector('button');
            btn.disabled = true;
            btn.innerHTML = '⏳ Processing... Please wait';
            btn.style.background = '#95a5a6';
        });
    </script>
</body>
</html>
"""
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        print(f"[+] HTML Dashboard Skeleton generated: data/processed/{filename}")
        return report_path